blank_issues_enabled: false
contact_links:
  - name: Fragen & Diskussionen
    url: https://github.com/AccellenceTechnologies/osap/discussions
    about: Nutze Discussions für allgemeine Fragen, Ideen und Roadmap-Themen.
